server:
  port: 8080

spring:
  application:
    name: config-default

  datasource:
    url: jdbc:mysql://localhost:3306/user_microdb
    username: root
    password: Deepali@aiopkp

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
